# Generated by Django 3.2.4 on 2021-09-20 13:10

from django.db import migrations, models
import django.db.models.deletion
import logging
logger = logging.getLogger(__name__)


def set_harvester(apps, _):
    from geonode.services import enumerations
    from geonode.harvesting.models import Harvester
    from geonode.harvesting.tasks import update_harvestable_resources
    from geonode.harvesting.utils import update_harvester_availability

    try:
        MyModel = apps.get_model('services', 'Service')
        _services_with_empty_harvesters = MyModel.objects.filter(
            type__in=(enumerations.WMS, enumerations.GN_WMS),
            harvester__isnull=True)
        for _service in _services_with_empty_harvesters:
            service_harvester = Harvester.objects.create(
                name=_service.name,
                default_owner=_service.owner,
                remote_url=_service.service_url,
                harvester_type=enumerations.HARVESTER_TYPES[_service.type]
            )
            update_harvester_availability(service_harvester)
            update_harvestable_resources.apply(args=(service_harvester.pk,))
            MyModel.objects.filter(id=_service.id).update(harvester=service_harvester)
    except Exception as e:
        logger.error(f'Error during set set_harvester: {e.args[0]}')


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0030_alter_harvester_num_harvestable_resources'),
        ('services', '0047_service_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='harvester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_harvester', to='harvesting.harvester'),
        ),
        migrations.RunPython(set_harvester, migrations.RunPython.noop)
    ]
